language: bash

services:
  - docker

env:
  matrix:
    - SOLR_VER=7.4.0 TAGS=7.4,7,latest
    - SOLR_VER=7.3.1 TAGS=7.3
    - SOLR_VER=7.2.1 TAGS=7.2
    - SOLR_VER=7.1.0 TAGS=7.1
    - SOLR_VER=6.6.5 TAGS=6.6,6
    - SOLR_VER=6.4.2 TAGS=6.4
    - SOLR_VER=5.5.5 TAGS=5.5,5
    - SOLR_VER=5.4.1 TAGS=5.4

script:
  - make && make test

after_success:
  - . "${TRAVIS_BUILD_DIR}/release.sh"
